apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-node-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-node-app
  template:
    metadata:
      labels:
        app: k8s-node-app
    spec:
      containers:
      - name: node-app
        image: varshakanugula17/k8s-node-app:v1
        ports:
        - containerPort: 3000
